runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /
    script: webapp.app
    secure: always

  - url: /loginpage
    script: webapp.app
    secure: always

  - url: /registration
    script: webapp.app
    secure: always

  - url: /register
    script: webapp.app
    secure: always

  - url: /login
    script: webapp.app
    secure: always

  - url: /logout
    script: webapp.app
    secure: always

  - url: /migrate
    script: webapp.app
    secure: always

  - url: /.*
    script: webapp.app
    secure: always

libraries:
  - name: jinja2
    version: latest
